arb-dir: lib/src/core/l10n/translations/
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
output-dir: lib/src/core/l10n/generated/

synthetic-package: false