name: vm_app
description: "VM App Flutter client"
publish_to: 'none'
version: 0.1.0

environment:
  flutter: ^3.41.0
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  ui_kit:
    path: packages/ui_kit

  # Core
  async: any
  collection: any
  meta: any
  stack_trace: any

  # State management
  control: ^0.2.0

  # Networking
  cronet_http: ^1.8.0
  cupertino_http: ^2.4.0
  http: ^1.6.0

  yandex_maps_mapkit_lite: 4.30.0-beta
  image_picker: ^1.2.1
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any # Use the pinned version from flutter_localizations

  # Storage
  shared_preferences: ^2.5.3

  # Logger
  l: ^5.0.1

  flutter_skill: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  vm_lints:
    path: packages/vm_lints

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files
  generate: true