name: ui_kit
description: "VM UI Kit"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.11.3
  flutter: ^3.41.0

dependencies:
  flutter:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  vm_lints:
    path: ../vm_lints

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 400
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          weight: 400
          style: italic
  shaders:
    - lib/src/components/shimmer/shimmer.frag
